version: '3'
services:
  app_postgres:
    container_name: app_postgres
    hostname: app_postgres
    image: postgres:latest
    networks:
      - net
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


  web:
    container_name: parser_backend
    networks:
      - net
    build:
      context: ./djangoProject
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

    command: python manage.py runserver 0.0.0.0:8001

    depends_on:
      - app_postgres
    env_file:
      - .env

  parser:
    container_name: parser
    networks:
      - net
    build:
      context: ./parser
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - app_postgres


networks:
  net:
