# Generated by Django 4.1.2 on 2023-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedSpecialist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.TextField()),
                ('living_place', models.TextField()),
                ('specialization', models.TextField()),
                ('category', models.TextField()),
                ('category_order', models.TextField()),
                ('email', models.TextField()),
                ('phonenumber', models.TextField()),
            ],
            options={
                'db_table': 'certified_specialist_cultar_objects_preservation',
            },
        ),
    ]
